"""create analytics table

Revision ID: 73c04bd4e2d4
Revises: a4e29b535301
Create Date: 2026-08-27 19:23:01.425468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c04bd4e2d4'
down_revision: Union[str, Sequence[str], None] = 'a4e29b535301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_clicked_at'), 'analytics', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_analytics_link_id'), 'analytics', ['link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_link_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_clicked_at'), table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
