"""add browser os device_type to analytics

Revision ID: 925935a288bb
Revises: da22821a4cd2
Create Date: 2026-08-27 23:50:44.251834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925935a288bb'
down_revision: Union[str, Sequence[str], None] = 'da22821a4cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('browser', sa.String(length=64), nullable=True))
    op.add_column('analytics', sa.Column('os', sa.String(length=64), nullable=True))
    op.add_column('analytics', sa.Column('device_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'device_type')
    op.drop_column('analytics', 'os')
    op.drop_column('analytics', 'browser')
    # ### end Alembic commands ###
