"""add country to analytics

Revision ID: da22821a4cd2
Revises: 9f9257167994
Create Date: 2026-08-27 20:37:31.516773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da22821a4cd2'
down_revision: Union[str, Sequence[str], None] = '9f9257167994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'country')
    # ### end Alembic commands ###
